force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the location coordinates for a city.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Coordinates__c.field-meta.xml
<CustomField>
    <fullName>Coordinates__c</fullName>
    <description>This field with store the Latitude and Longitude of a certain place or city.</description>
    <label>Coordinates</label>
    <required>true</required>
    <scale>5</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/WeatherInfo__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store the weather information like temperature, description etc.</description>
    <label>Weather Info</label>
    <nameField>
        <displayFormat>W{000000}</displayFormat>
        <label>Weather Info Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Weather Info</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WeatherInfo__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>To store any other weather information</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Humidity__c.field-meta.xml
<CustomField>
    <fullName>Humidity__c</fullName>
    <description>This field will store the location humidity in percentage format.</description>
    <label>Humidity %</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>This field will store the icon to display for the weather conditions.</description>
    <label>Icon</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Foreign key to Location object.</description>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Weather Info</relationshipLabel>
    <relationshipName>Weather_Info</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Temperature_Degree_celcius__c.field-meta.xml
<CustomField>
    <fullName>Temperature_Degree_celcius__c</fullName>
    <description>This field will store the temperature for the city in Celsius format.</description>
    <label>Temperature (Degree Celsius)</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WeatherInfo__c/fields/Wind_Speed__c.field-meta.xml
<CustomField>
    <fullName>Wind_Speed__c</fullName>
    <description>To store the wind speed in metre/sec</description>
    <inlineHelpText>Wind speed in metre/sec</inlineHelpText>
    <label>Wind Speed</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WeatherDisplayController.cls
public without sharing class WeatherDisplayController {
    @AuraEnabled
    public static WeatherInfo__c getWeatherInfo(String locationId) {
        List<WeatherInfo__c> weatherInfoList=new List<WeatherInfo__c>();
        weatherInfoList=[SELECT Icon__c,Humidity__c,Wind_Speed__c,Temperature_Degree_celcius__c, Description__c,Location__r.Name,CreatedDate FROM WeatherInfo__c WHERE Location__c = :locationId AND CreatedDate >= :DateTime.now().addMinutes(-5) LIMIT 1];

        if(weatherInfoList.isEmpty()){
            Location__c location=[Select Id,Name,Coordinates__c FROM Location__c WHERE Id=:locationId];
            weatherInfoList.add(WeatherIntegrationService.fetchWeatherInfo(location));
        }
        if(!weatherInfoList.isEmpty()){
            return weatherInfoList[0];
        }else{
            return null;
        }
    }
}